export default {
  background_color: '',
  properties: [
    {
      function: {
        index: 1,
        name: '布尔值大模块开关',
        subject: 'boolean_big_btn',
        type: 'BOOLEAN',
        up: true,
        down: true,
      },
      type: 'BIG',
      icon: '',
      background: 'file',
    },
    {
      function: {
        index: 2,
        name: '数值型大模块按钮',
        subject: 'number_big_btn',
        type: 'NUMBER',
        up: true,
        down: true,
        min: 10,
        max: 30,
        step: 1,
      },
      type: 'BIG',
      icon: '',
      background: 'file',
    },
    {
      function: {
        index: 3,
        name: '枚举型大模块按钮',
        subject: 'enum_big_btn',
        type: 'ENUM',
        up: true,
        down: true,
        enum: ['自动', '制热', '除湿', 'ECO', '制冷', '通风'],
      },
      type: 'BIG',
      icon: '',
      background: 'file',
    },
    {
      function: {
        index: 4,
        name: '字符型大模块按钮',
        subject: 'string_big_btn',
        type: 'STRING',
        up: true,
        down: true,
      },
      type: 'BIG',
      icon: '',
      background: 'file',
    },
    {
      function: {
        index: 5,
        name: '布尔值中模块开关',
        subject: 'boolean_middle_btn',
        type: 'BOOLEAN',
        up: true,
        down: true,
      },
      type: 'MIDDLE',
      icon: '',
      background: 'file',
    },
    {
      function: {
        index: 6,
        name: '数值型中模块按钮',
        subject: 'number_middle_btn',
        type: 'NUMBER',
        up: true,
        down: true,
        min: 15,
        max: 30,
        step: 1,
      },
      type: 'MIDDLE',
      icon: '',
      background: 'file',
    },
    {
      function: {
        index: 7,
        name: '枚举型中模块按钮',
        subject: 'enum_middle_btn',
        type: 'ENUM',
        up: true,
        down: true,
        enum: ['自动', '制热', '除湿', 'ECO', '制冷', '通风'],
      },
      type: 'MIDDLE',
      icon: '',
      background: 'file',
    },
    {
      function: {
        index: 8,
        name: '字符型中模块按钮',
        subject: 'string_middle_btn',
        type: 'STRING',
        up: true,
        down: true,
      },
      type: 'MIDDLE',
      icon: '',
      background: 'file',
    },
    {
      function: {
        index: 9,
        name: '字符型小模块按钮1',
        subject: 'string_small_btn',
        type: 'STRING',
        up: true,
        down: true,
      },
      type: 'SMALL',
      icon: '',
      background: 'file',
    },
    {
      function: {
        index: 10,
        name: '字符型小模块按钮2',
        subject: 'string_small_btn',
        type: 'STRING',
        up: true,
        down: true,
      },
      type: 'SMALL',
      icon: '',
      background: 'file',
    },
    {
      function: {
        index: 11,
        name: '字符型小模块按钮3',
        subject: 'string_small_btn',
        type: 'STRING',
        up: true,
        down: true,
      },
      type: 'SMALL',
      icon: '',
      background: 'file',
    },
    {
      function: {
        index: 12,
        name: '字符型小模块按钮4',
        subject: 'string_small_btn',
        type: 'STRING',
        up: true,
        down: true,
      },
      type: 'SMALL',
      icon: '',
      background: 'file',
    },
  ],
};
