export default {
  mode: 'custom',
  data: {
    template: {
      _id: '111122223333444455550051',
      app_id: '111122223333444455550031',
      background_color: ' 0xEEEEEE',
      switch: '111122223333444455550041',
      properties: [
        {
          function_id: '1',
          type: 'BIG',
          icon: 'xxxxxx-b',
          background: 'xxxxxx-c',
        },
        {
          function_id: '2',
          type: 'BIG',
          icon: 'xxxxxx-b',
          background: 'xxxxxx-c',
        },
        {
          function_id: '3',
          type: 'BIG',
          icon: 'xxxxxx-b',
          background: 'xxxxxx-c',
        },
        {
          function_id: '4',
          type: 'BIG',
          icon: 'xxxxxx-b',
          background: 'xxxxxx-c',
        },
        {
          function_id: '5',
          type: 'MIDDLE',
          icon: 'xxxxxx-b',
          background: 'xxxxxx-c',
        },
        {
          function_id: '6',
          type: 'MIDDLE',
          icon: 'xxxxxx-b',
          background: 'xxxxxx-c',
        },
        {
          function_id: '7',
          type: 'MIDDLE',
          icon: 'xxxxxx-b',
          background: 'xxxxxx-c',
        },
        {
          function_id: '8',
          type: 'MIDDLE',
          icon: 'xxxxxx-b',
          background: 'xxxxxx-c',
        },
      ],
    },
    functions: [
      {
        _id: '1',
        product_id: '111122223333444455550021',
        index: 1,
        name: '布尔值大模块开关',
        subject: 'boolean_big_btn',
        type: 'BOOLEAN',
        up: true,
        down: true,
      },
      {
        _id: '2',
        product_id: '111122223333444455550021',
        index: 2,
        name: '数值型大模块按钮',
        subject: 'number_big_btn',
        type: 'NUMBER',
        up: true,
        down: true,
        number: {
          max: 32,
          min: 18,
          step: 1,
        },
      },
      {
        _id: '3',
        product_id: '111122223333444455550021',
        index: 3,
        name: '枚举型大模块按钮',
        subject: 'enum_big_btn',
        type: 'ENUM',
        up: true,
        down: true,
        enum: ['自动', '制热', '除湿', 'ECO', '制冷', '通风'],
      },
      {
        _id: '4',
        product_id: '111122223333444455550021',
        index: 4,
        name: '字符型大模块按钮',
        subject: 'string_big_btn',
        type: 'STRING',
        up: true,
        down: true,
      },
      {
        _id: '5',
        product_id: '111122223333444455550021',
        index: 5,
        name: '布尔值中模块开关',
        subject: 'boolean_middle_btn',
        type: 'BOOLEAN',
        up: true,
        down: true,
      },
      {
        _id: '6',
        product_id: '111122223333444455550021',
        index: 6,
        name: '数值型中模块按钮',
        subject: 'number_middle_btn',
        type: 'NUMBER',
        up: true,
        down: true,
        number: {
          max: 30,
          min: 15,
          step: 1,
        },
      },
      {
        _id: '7',
        product_id: '111122223333444455550021',
        index: 7,
        name: '枚举型中模块按钮',
        subject: 'enum_big_btn',
        type: 'ENUM',
        up: true,
        down: true,
        enum: ['自动', '制热', '除湿', 'ECO', '制冷', '通风'],
      },
      {
        _id: '8',
        product_id: '111122223333444455550021',
        index: 8,
        name: '字符型中模块按钮',
        subject: 'string_middle_btn',
        type: 'STRING',
        up: true,
        down: true,
      },
    ],
  },
};
